CREATE TABLE TBL_PROVEEDOR(
    PROVEEDOR_ID NUMERIC(6) NOT NULL PRIMARY KEY,
    RAZON_SOCIAL VARCHAR2(220) NOT NULL UNIQUE,
    RUC CHAR(11) NOT NULL UNIQUE,
    CORREO VARCHAR2(60) NOT NULL ,
    TELEFONO VARCHAR2(120) NOT NULL ,
     ESTADO CHAR(1) DEFAULT '1' NOT NULL 
);



INSERT INTO TBL_PROVEEDOR(PROVEEDOR_ID,RAZON_SOCIAL,RUC,CORREO,TELEFONO) 
VALUES(1, 'GALAXY TRAINING PERU','20234564542','contacto@galaxy.edu.pe','+51 950 4506');

COMMIT;
